// The workflow graph's vocabulary, shared by the Curator board, the payload
// converters and the read-only view.
//
// It mirrors backend/project/workflow.py deliberately and exactly. The server
// is the authority -- it refuses a graph it cannot store -- and this half
// exists so a curator is told BEFORE they save, not after. If the two ever
// disagree, the server wins and this file is the one that is wrong.

// Artifact id prefixes, as the Curator mints them (`type.charAt(0)`):
// charts -> c, scripts -> s, datasets -> d, tools -> t, heads -> h.
export const CHART = "c";
export const SCRIPT = "s";
export const DATASET = "d";
export const TOOL = "t";
export const EXTERNAL = "h";

export const CONSUMES = "consumes";
export const USES_TOOL = "uses_tool";
export const GENERATES = "generates";
// One stage of the work feeding the next: same kind to same kind, directed
// upstream -> downstream. `preprocess.py feeds into plot.py`.
//
// A same-kind pair can hold this OR `related_to`, and which one is true is
// something only the curator knows -- so it is offered as a choice and never
// inferred for them.
export const FEEDS_INTO = "feeds_into";

// THE OTHER CLASS OF EDGE: these two belong together.
//
// `related_to` states no order and no data flow. Two figures of the same
// system, two datasets from one run, two tools that go together -- a curator
// can say so without claiming one produced the other.
//
// Same kind only, because a relationship ACROSS kinds already has a directed
// name, and offering a vaguer second one would let the same fact be recorded
// two different ways.
export const RELATED_TO = "related_to";

// Which endpoints each relationship may join, by id prefix.
const KINDS = [CHART, SCRIPT, DATASET, TOOL, EXTERNAL];

export const EDGE_RULES = {
  [CONSUMES]: { from: [DATASET, EXTERNAL], to: [SCRIPT, CHART] },
  [USES_TOOL]: { from: [TOOL], to: [SCRIPT] },
  [GENERATES]: { from: [SCRIPT], to: [CHART] },
  [FEEDS_INTO]: { from: KINDS, to: KINDS },
  [RELATED_TO]: { from: KINDS, to: KINDS },
};

/** Relationships that also require both ends to be the same kind. */
export const SAME_KIND = [FEEDS_INTO, RELATED_TO];

/** Relationships that state no direction. */
export const UNDIRECTED = [RELATED_TO];

/** The relationships that describe a flow, and so can close a loop. */
export const DIRECTED = Object.keys(EDGE_RULES).filter(
  (type) => !UNDIRECTED.includes(type)
);

/** True when this relationship may join these two id prefixes. */
export const edgeFits = (type, from, to) => {
  const rule = EDGE_RULES[type];
  if (!rule) return false;
  if (!rule.from.includes(from) || !rule.to.includes(to)) return false;
  return !SAME_KIND.includes(type) || from === to;
};

/** True when these two already hold an undirected relationship, either way. */
export const hasRelation = (edges, a, b, type) =>
  (edges || []).some((edge) => {
    const parsed = fromStoredEdge(edge);
    if (parsed.type !== type) return false;
    return (
      (parsed.from === a && parsed.to === b) ||
      (parsed.from === b && parsed.to === a)
    );
  });

/**
 * How an edge READS, as a sentence: `${from} ${verb} ${to}`.
 *
 * One vocabulary for the whole product -- the curator's outline, the link
 * dialog and the published summary all say the same words for the same
 * relationship, and every one of them is written subject-first so the
 * direction is in the sentence rather than in the indentation.
 */
export const EDGE_VERB = {
  [GENERATES]: "generates",
  [CONSUMES]: "supplies input to",
  [USES_TOOL]: "is used by",
  [FEEDS_INTO]: "feeds into",
  [RELATED_TO]: "related to",
};

/** The heading a parent puts above children joined by this relationship. */
export const EDGE_GROUP = {
  [GENERATES]: "Generated by",
  [CONSUMES]: "Uses input",
  [USES_TOOL]: "Uses tool",
  [FEEDS_INTO]: "Receives from script",
  [RELATED_TO]: "Related resources",
};

/**
 * How an edge reads as a sentence.
 *
 * A directed one is written with arrows, subject first, so the flow is in the
 * words. An undirected one is written with a double-headed connector and no
 * subject at all, because neither end came first.
 */
export const edgeSentence = (edge, name) =>
  UNDIRECTED.includes(edge.type)
    ? `${name(edge.from)} ↔ ${EDGE_VERB[edge.type]} ↔ ${name(edge.to)}`
    : `${name(edge.from)} → ${EDGE_VERB[edge.type] || "connects to"} → ${name(
        edge.to
      )}`;

// The three lanes a reader sees. A workflow reads left to right: what went
// in, what was run, what came out.
export const INPUTS = "inputs";
export const PROCESS = "process";
export const OUTPUTS = "outputs";

const LANE_BY_PREFIX = {
  [DATASET]: INPUTS,
  [EXTERNAL]: INPUTS,
  [SCRIPT]: PROCESS,
  [TOOL]: PROCESS,
  [CHART]: OUTPUTS,
};

export const prefixOf = (id) => String(id || "").charAt(0);

/** Which lane an artifact belongs in, or "" for an id this code does not know. */
export const laneOf = (id) => LANE_BY_PREFIX[prefixOf(id)] || "";

/**
 * The relationship two artifacts can have, or "" when they can have none.
 *
 * This is what lets the contextual Add buttons connect things without asking:
 * given "a Script was added while a Chart was selected", the only relationship
 * those two can hold is `generates`, so there is nothing to ask about. It is
 * never a guess -- when a pair could hold more than one relationship, or none,
 * this returns "" and the curator connects them explicitly.
 */
export const inferEdgeType = (fromId, toId) => {
  const from = prefixOf(fromId);
  const to = prefixOf(toId);
  const matches = DIRECTED.filter((type) => edgeFits(type, from, to));
  return matches.length === 1 ? matches[0] : "";
};

/**
 * One stored edge -> {from, to, type}. `type` is "" for a legacy pair.
 *
 * Both shapes arrive: `{from, to, type}` is what V1 writes, `["from", "to"]`
 * is what every earlier record holds. Reading only one of them is the bug
 * this replaces -- a typed edge read as an array yields two undefineds.
 */
export const fromStoredEdge = (edge) => {
  if (Array.isArray(edge)) {
    return { from: edge[0] || "", to: edge[1] || "", type: "" };
  }
  if (edge && typeof edge === "object") {
    const read = {
      from: edge.from || "",
      to: edge.to || "",
      type: edge.type || "",
    };
    // `feedback` is a FACT THE CURATOR STATED, not something to recompute.
    // Whether the graph currently contains a loop changes as other edges come
    // and go; whether this connection was confirmed as a feedback loop does
    // not, so it is read back rather than derived. Absent on a legacy edge,
    // and never invented for one.
    return edge.feedback ? { ...read, feedback: true } : read;
  }
  return { from: "", to: "", type: "" };
};

/**
 * {from, to, type} -> what is persisted.
 *
 * A typed edge is written as an object. An UNTYPED one is written back as the
 * pair it arrived as, so opening a legacy record and saving it does not
 * silently rewrite its graph into a shape it never had.
 */
export const toStoredEdge = (edge) => {
  if (!edge || !edge.type) return [edge.from, edge.to];
  const stored = { from: edge.from, to: edge.to, type: edge.type };
  return edge.feedback ? { ...stored, feedback: true } : stored;
};

/**
 * Why this edge cannot be added, or "" if it can.
 *
 * `knownIds` is every artifact id the paper holds. The checks are the
 * server's, in the same order, so the two give the same answer.
 */
export const edgeProblem = (edge, knownIds, existingEdges = []) => {
  const { from, to, type } = fromStoredEdge(edge);
  if (!from || !to) return "That connection is missing an endpoint.";
  if (from === to) return "A node cannot be connected to itself.";

  const known = new Set(knownIds || []);
  if (!known.has(from) || !known.has(to)) {
    return "That connection refers to something this paper does not have.";
  }
  if (type) {
    if (!EDGE_RULES[type]) return `Unknown relationship '${type}'.`;
    if (!edgeFits(type, prefixOf(from), prefixOf(to))) {
      return "Those two cannot be connected that way.";
    }
  }
  if (UNDIRECTED.includes(type)) {
    // One fact, however it is ordered -- and no direction to loop.
    if (hasRelation(existingEdges, from, to, type)) {
      return "Those two are already related to each other.";
    }
    return "";
  }
  // A loop is NOT a problem here. It is a feedback loop the curator has to
  // confirm first -- see `closesLoop`, which the Curator asks about before
  // making the edge, and which marks the result so a reader can tell a
  // deliberate loop from a mistake.
  return "";
};

/** Only the edges that claim a direction, and so can form a loop. */
export const flowingOnly = (edges) =>
  (edges || []).filter(
    (edge) => !UNDIRECTED.includes(fromStoredEdge(edge).type)
  );

/**
 * True when this connection would close a feedback loop.
 *
 * Undirected associations are left out: they state no order, so a pair of
 * them is not a loop in any sense worth asking about.
 */
export const closesLoop = (edges, candidate) => {
  if (!candidate || UNDIRECTED.includes(candidate.type)) return false;
  const { from, to } = fromStoredEdge(candidate);
  if (!from || !to) return false;
  if (from === to) return true;

  // Whether THIS edge closes a loop, which is not the same question as
  // whether the graph contains one. Asking the second while adding several
  // links at once marks every edge after the first loop as a loop too.
  const adjacency = new Map();
  flowingOnly(edges)
    .map(fromStoredEdge)
    .forEach((edge) => {
      if (!adjacency.has(edge.from)) adjacency.set(edge.from, []);
      adjacency.get(edge.from).push(edge.to);
    });

  const seen = new Set([to]);
  const stack = [to];
  while (stack.length) {
    const node = stack.pop();
    if (node === from) return true;
    for (const next of adjacency.get(node) || []) {
      if (seen.has(next)) continue;
      seen.add(next);
      stack.push(next);
    }
  }
  return false;
};

/**
 * The connected components of a paper's graph, as arrays of ids.
 *
 * Connectivity here is UNDIRECTED and includes associations: two artifacts
 * joined any way at all are part of the same piece of work, and that is what
 * a curator means by "one workflow". Components are DERIVED on every render
 * from the artifacts and edges that exist -- there is no group model, nothing
 * to migrate, and connecting two groups merges them while removing the last
 * edge between them splits them again, with no extra code.
 *
 * Returns [connected components (2+ members), lone ids], each sorted, and the
 * components ordered by their first member so the page does not reshuffle.
 */
export const componentsOf = (ids, edges) => {
  const parent = new Map((ids || []).map((id) => [id, id]));
  const find = (id) => {
    let root = id;
    while (parent.get(root) !== root) root = parent.get(root);
    let walk = id;
    while (parent.get(walk) !== walk) {
      const next = parent.get(walk);
      parent.set(walk, root);
      walk = next;
    }
    return root;
  };
  const union = (a, b) => {
    const ra = find(a);
    const rb = find(b);
    if (ra !== rb) parent.set(ra, rb);
  };

  (edges || []).forEach((edge) => {
    const { from, to } = fromStoredEdge(edge);
    if (parent.has(from) && parent.has(to)) union(from, to);
  });

  const groups = new Map();
  (ids || []).forEach((id) => {
    const root = find(id);
    if (!groups.has(root)) groups.set(root, []);
    groups.get(root).push(id);
  });

  const connected = [];
  const alone = [];
  Array.from(groups.values()).forEach((members) => {
    const sorted = members.slice().sort();
    if (sorted.length > 1) connected.push(sorted);
    else alone.push(sorted[0]);
  });
  connected.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  return { connected, alone: alone.sort() };
};

/** True when adding `candidate` to `edges` would close a cycle. */
export const wouldCycle = (edges, candidate) => {
  const adjacency = new Map();
  const add = (edge) => {
    const { from, to } = fromStoredEdge(edge);
    if (!from || !to) return;
    if (!adjacency.has(from)) adjacency.set(from, []);
    adjacency.get(from).push(to);
  };
  (edges || []).forEach(add);
  if (candidate) add(candidate);

  // Iterative DFS: a graph is curator input, so a long chain must produce an
  // answer rather than a stack overflow.
  const state = new Map(); // 1 = in progress, 2 = done
  for (const start of Array.from(adjacency.keys())) {
    if (state.get(start)) continue;
    const stack = [[start, (adjacency.get(start) || [])[Symbol.iterator]()]];
    state.set(start, 1);
    while (stack.length) {
      const [node, children] = stack[stack.length - 1];
      let advanced = false;
      let step = children.next();
      while (!step.done) {
        const child = step.value;
        const status = state.get(child);
        if (status === 1) return true;
        if (!status) {
          state.set(child, 1);
          stack.push([child, (adjacency.get(child) || [])[Symbol.iterator]()]);
          advanced = true;
          break;
        }
        step = children.next();
      }
      if (!advanced) {
        state.set(node, 2);
        stack.pop();
      }
    }
  }
  return false;
};

/** True when this exact connection is already present, in either shape. */
export const hasEdge = (edges, from, to) =>
  (edges || []).some((edge) => {
    const parsed = fromStoredEdge(edge);
    return parsed.from === from && parsed.to === to;
  });
