/**
 * The published workflow section.
 *
 * A workflow of any size printed as a nested "connected to:" list ran for
 * screens before the graph was reached, so the shape of the thing -- which
 * is the whole point of a graph -- arrived second. The picture goes first now
 * and the words move behind a closed toggle.
 *
 * The words are NOT deleted. The graph is a canvas: unreadable with a screen
 * reader, poor on a phone. For some readers of a published record it is the
 * only form of the workflow they can get at.
 */
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

// vis-network draws to a canvas jsdom does not have, and none of these
// assertions are about the drawing.
jest.mock("../components/Workflow/Graph", () => {
  const Stub = () => <div data-testid="stub-graph" />;
  return Stub;
});
jest.mock("../components/Workflow/Legend", () => {
  const Stub = () => <div data-testid="stub-legend" />;
  return Stub;
});

import Workflow from "../components/Paper/Workflow";

const PAPER = {
  workflow: {
    nodes: [],
    edges: [{ from: "s0", to: "c0", type: "generates" }],
  },
  charts: [{ id: "c0", caption: "Density of states", imageFile: "figures/dos.png" }],
  scripts: [{ id: "s0", readme: "plot_dos.py", files: ["figures/dos.ipynb"] }],
  datasets: [],
  tools: [],
  external: [],
};

const open = () => render(<Workflow {...PAPER} />);

describe("the published workflow section", () => {
  it("shows the graph without being asked", () => {
    open();
    expect(screen.getByTestId("stub-graph")).toBeInTheDocument();
    expect(screen.getByTestId("stub-legend")).toBeInTheDocument();
  });

  it("does not print the whole list on arrival", () => {
    open();
    expect(screen.queryByTestId("workflow-words")).not.toBeInTheDocument();
    expect(screen.queryByText(/connected to:|generated by:/i)).not.toBeInTheDocument();
  });

  it("offers the words as a closed, announced toggle", () => {
    open();
    const toggle = screen.getByTestId("workflow-words-toggle");
    expect(toggle).toHaveTextContent(/workflow in words/i);
    expect(toggle).toHaveAttribute("aria-expanded", "false");
  });

  it("still gives a reader the workflow in words on request", async () => {
    const user = userEvent.setup({ delay: null });
    open();
    await user.click(screen.getByTestId("workflow-words-toggle"));

    expect(screen.getByTestId("workflow-words")).toBeInTheDocument();
    expect(screen.getByTestId("workflow-words-toggle")).toHaveAttribute(
      "aria-expanded",
      "true"
    );
    // The relationship itself, not just a box appearing.
    expect(screen.getByTestId("workflow-words")).toHaveTextContent(
      /plot_dos\.py/i
    );
  });

  it("closes again", async () => {
    const user = userEvent.setup({ delay: null });
    open();
    const toggle = screen.getByTestId("workflow-words-toggle");
    await user.click(toggle);
    await user.click(toggle);

    // The control says so at once; the collapse unmounts when its transition
    // ends, which is a frame later.
    expect(toggle).toHaveAttribute("aria-expanded", "false");
    await waitFor(() =>
      expect(screen.queryByTestId("workflow-words")).not.toBeInTheDocument()
    );
  });
});
