/**
 * The published workflow, read-only.
 *
 * A reader arrives asking "where did this figure come from", so the section is
 * organised by figure and says the relationship in words. It is structurally
 * read-only: there is no edit affordance here at all, because the place to
 * change a workflow is the Curator.
 */
import { render, screen, within } from "@testing-library/react";

import WorkflowSummary from "../components/Paper/WorkflowSummary";

const PAPER = {
  charts: [
    { id: "c0", caption: "Density of states" },
    { id: "c1", caption: "Lifetime vs. dose" },
  ],
  scripts: [{ id: "s0", readme: "plot_dos.py" }],
  datasets: [{ id: "d0", readme: "Cryogenic spectra" }],
  tools: [{ id: "t0", packageName: "numpy 1.26.4" }],
  external: [
    {
      id: "h0",
      label: "Materials Project mp-21276",
      readme: "Reference band structure.",
      URLs: ["https://materialsproject.org/materials/mp-21276"],
    },
  ],
};

const renderSummary = (edges, overrides = {}) =>
  render(
    <WorkflowSummary
      workflow={{ nodes: [], edges }}
      {...PAPER}
      {...overrides}
    />
  );

const FULL = [
  { from: "d0", to: "s0", type: "consumes" },
  { from: "h0", to: "s0", type: "consumes" },
  { from: "t0", to: "s0", type: "uses_tool" },
  { from: "s0", to: "c0", type: "generates" },
];

describe("what a reader is shown", () => {
  it("is organised by figure", () => {
    renderSummary(FULL);
    const figure = screen.getByTestId("workflow-summary-figure-c0");
    expect(figure).toHaveTextContent("Density of states");
    // A chart nothing points at is not given an empty entry.
    expect(
      screen.queryByTestId("workflow-summary-figure-c1")
    ).not.toBeInTheDocument();
  });

  it("says the actual relationship in words", () => {
    renderSummary(FULL);
    const figure = screen.getByTestId("workflow-summary-figure-c0");
    expect(figure).toHaveTextContent(/generated by/i);
    expect(figure).toHaveTextContent(/uses tool/i);
    expect(figure).toHaveTextContent(/uses:/i);
    // The stored code is never shown to a reader.
    expect(figure).not.toHaveTextContent("uses_tool");
    expect(figure).not.toHaveTextContent("consumes");
  });

  it("follows the chain from a figure back to its inputs", () => {
    renderSummary(FULL);
    const figure = screen.getByTestId("workflow-summary-figure-c0");
    expect(figure).toHaveTextContent("plot_dos.py");
    expect(figure).toHaveTextContent("Cryogenic spectra");
    expect(figure).toHaveTextContent("numpy 1.26.4");
    expect(figure).toHaveTextContent("Materials Project mp-21276");
  });

  it("links a local artifact to the section that shows it in full", () => {
    renderSummary(FULL);
    expect(
      screen.getByRole("link", { name: /density of states/i })
    ).toHaveAttribute("href", "#charts");
    expect(
      screen.getByRole("link", { name: /plot_dos\.py/i })
    ).toHaveAttribute("href", "#scripts");
    expect(
      screen.getByRole("link", { name: /cryogenic spectra/i })
    ).toHaveAttribute("href", "#datasets");
    expect(
      screen.getByRole("link", { name: /numpy/i })
    ).toHaveAttribute("href", "#tools");
  });

  it("sends external data out, and marks it as external", () => {
    renderSummary(FULL);
    const link = screen.getByRole("link", { name: /materials project/i });
    expect(link).toHaveAttribute(
      "href",
      "https://materialsproject.org/materials/mp-21276"
    );
    expect(link).toHaveAttribute("target", "_blank");
    expect(link.getAttribute("rel")).toContain("noopener");
    expect(screen.getByTestId("workflow-summary")).toHaveTextContent(/\(external\)/i);
  });

  it("never offers a way to change the workflow", () => {
    renderSummary(FULL);
    const summary = screen.getByTestId("workflow-summary");
    expect(within(summary).queryAllByRole("button")).toHaveLength(0);
    expect(summary.textContent).not.toMatch(/unlink|connect|attach|edit/i);
  });
});

describe("legacy and empty records", () => {
  it("renders nothing at all when there is no workflow", () => {
    const { container } = render(
      <WorkflowSummary workflow={{ nodes: [], edges: [] }} {...PAPER} />
    );
    expect(container).toBeEmptyDOMElement();
  });

  it("renders nothing when the workflow key is missing entirely", () => {
    const { container } = render(<WorkflowSummary {...PAPER} />);
    expect(container).toBeEmptyDOMElement();
  });

  it("reads a legacy untyped graph without inventing a relationship", () => {
    // A pair says only that the two are connected, which is all the record
    // actually claims. Saying "generated by" would be a claim nobody made.
    renderSummary([["s0", "c0"], ["d0", "s0"]]);
    const figure = screen.getByTestId("workflow-summary-figure-c0");
    expect(figure).toHaveTextContent(/connected to/i);
    expect(figure).not.toHaveTextContent(/generated by/i);
    expect(figure).toHaveTextContent("plot_dos.py");
  });

  it("reads a graph that mixes typed and untyped edges", () => {
    renderSummary([
      ["d0", "s0"],
      { from: "s0", to: "c0", type: "generates" },
    ]);
    const figure = screen.getByTestId("workflow-summary-figure-c0");
    expect(figure).toHaveTextContent(/generated by/i);
    expect(figure).toHaveTextContent(/connected to/i);
  });

  it("shows a legacy external node with no label", () => {
    renderSummary([{ from: "h0", to: "s0", type: "consumes" },
                   { from: "s0", to: "c0", type: "generates" }],
                  { external: [{ id: "h0", readme: "From a collaborator" }] });
    expect(screen.getByTestId("workflow-summary")).toHaveTextContent(
      /from a collaborator/i
    );
  });

  it("shows no link for an external node holding a local path", () => {
    renderSummary([{ from: "h0", to: "s0", type: "consumes" },
                   { from: "s0", to: "c0", type: "generates" }],
                  { external: [{ id: "h0", label: "Local copy",
                                 URLs: ["/home/curator/secret.h5"] }] });
    expect(screen.getByTestId("workflow-summary")).toHaveTextContent("Local copy");
    expect(
      screen.queryByRole("link", { name: /local copy/i })
    ).not.toBeInTheDocument();
  });
});

describe("resources that feed no figure", () => {
  it("are still shown rather than dropped", () => {
    // A dataset wired to a script that produces nothing is still part of the
    // record.
    renderSummary([{ from: "d0", to: "s0", type: "consumes" }]);
    const other = screen.getByTestId("workflow-summary-other");
    expect(other).toHaveTextContent("Cryogenic spectra");
    expect(other).toHaveTextContent("plot_dos.py");
  });

  it("are not listed when everything feeds a figure", () => {
    renderSummary(FULL);
    expect(
      screen.queryByTestId("workflow-summary-other")
    ).not.toBeInTheDocument();
  });
});

// Script -> Script reaches the published record like every other typed edge.
describe("a script that feeds another script", () => {
  const CHAIN = [
    { from: "s1", to: "s0", type: "feeds_into" },
    { from: "s0", to: "c0", type: "generates" },
  ];
  const TWO_SCRIPTS = {
    scripts: [
      { id: "s0", readme: "plot_dos.py" },
      { id: "s1", readme: "preprocess.py" },
    ],
  };

  it("says feeds into, in words a reader knows", () => {
    renderSummary(CHAIN, TWO_SCRIPTS);
    expect(screen.getByTestId("workflow-summary")).toHaveTextContent(
      /feeds into/i
    );
    expect(screen.getByTestId("workflow-summary")).toHaveTextContent(
      "preprocess.py"
    );
  });

  it("never shows the stored key to a reader", () => {
    renderSummary(CHAIN, TWO_SCRIPTS);
    expect(screen.getByTestId("workflow-summary")).not.toHaveTextContent(
      "feeds_into"
    );
  });

  it("keeps the figure as the thing the list is about", () => {
    renderSummary(CHAIN, TWO_SCRIPTS);
    expect(
      screen.getByTestId("workflow-summary-figure-c0")
    ).toBeInTheDocument();
  });
});

// The undirected relationship reaches the published record too, and must not
// pick up a direction on the way.
describe("resources that are merely related", () => {
  const TWO_FIGURES = {
    charts: [
      { id: "c0", caption: "Density of states", imageFile: "figures/dos.png" },
      { id: "c1", caption: "Band structure", imageFile: "figures/bands.png" },
    ],
  };

  it("says related to, with no arrow and no producer", () => {
    renderSummary(
      [{ from: "c1", to: "c0", type: "related_to" }],
      TWO_FIGURES
    );
    const summary = screen.getByTestId("workflow-summary");
    expect(summary).toHaveTextContent(/related to/i);
    expect(summary).toHaveTextContent("Band structure");
    // "generated by" would claim one figure produced the other.
    expect(summary).not.toHaveTextContent(/generated by/i);
  });

  it("never shows the stored key to a reader", () => {
    renderSummary([{ from: "c1", to: "c0", type: "related_to" }], TWO_FIGURES);
    expect(screen.getByTestId("workflow-summary")).not.toHaveTextContent(
      "related_to"
    );
  });

  it("leaves the directed relationships reading as before", () => {
    renderSummary(FULL);
    const summary = screen.getByTestId("workflow-summary");
    expect(summary).toHaveTextContent(/generated by/i);
    expect(summary).toHaveTextContent(/uses tool/i);
    expect(summary).not.toHaveTextContent(/related to/i);
  });
});
